-- This module is the root of the TwoPersonGamesLemmaCanonicalLaneLean Lean proof package.
-- It imports all submodules necessary for the formalization of two-person games,
-- including Nash equilibrium, minimax theorem, bargaining solutions, and mechanism design.
-- The naming convention follows the PoincareConjectureCanonicalLaneLean package.

import TwoPersonGamesLemmaCanonicalLaneLean.Basic
import TwoPersonGamesLemmaCanonicalLaneLean.SourcePackage
import TwoPersonGamesLemmaCanonicalLaneLean.SourceDependencies
import TwoPersonGamesLemmaCanonicalLaneLean.Formalization
import TwoPersonGamesLemmaCanonicalLaneLean.ReviewerBridge
import TwoPersonGamesLemmaCanonicalLaneLean.TheoremStatement
import TwoPersonGamesLemmaCanonicalLaneLean.MathlibObjects
import TwoPersonGamesLemmaCanonicalLaneLean.AdmissibleClass
import TwoPersonGamesLemmaCanonicalLaneLean.Projection
import TwoPersonGamesLemmaCanonicalLaneLean.BridgeLemmas
import TwoPersonGamesLemmaCanonicalLaneLean.GateLemmas
import TwoPersonGamesLemmaCanonicalLaneLean.FinalTheorem
import TwoPersonGamesLemmaCanonicalLaneLean.NormalFormGame
import TwoPersonGamesLemmaCanonicalLaneLean.PureStrategy
import TwoPersonGamesLemmaCanonicalLaneLean.MixedStrategy
import TwoPersonGamesLemmaCanonicalLaneLean.BestResponse
import TwoPersonGamesLemmaCanonicalLaneLean.NashEquilibrium
import TwoPersonGamesLemmaCanonicalLaneLean.ZeroSum
import TwoPersonGamesLemmaCanonicalLaneLean.Minimax
import TwoPersonGamesLemmaCanonicalLaneLean.SaddlePoint
import TwoPersonGamesLemmaCanonicalLaneLean.BargainingProblem
import TwoPersonGamesLemmaCanonicalLaneLean.NashBargainingSolution
import TwoPersonGamesLemmaCanonicalLaneLean.KalaiSmorodinsky
import TwoPersonGamesLemmaCanonicalLaneLean.MechanismDesign
import TwoPersonGamesLemmaCanonicalLaneLean.SocialChoice
import TwoPersonGamesLemmaCanonicalLaneLean.IncentiveCompatibility
import TwoPersonGamesLemmaCanonicalLaneLean.RevelationPrinciple
import TwoPersonGamesLemmaCanonicalLaneLean.FolkTheorem
import TwoPersonGamesLemmaCanonicalLaneLean.CooperativeGames
import TwoPersonGamesLemmaCanonicalLaneLean.RepeatedGames
import TwoPersonGamesLemmaCanonicalLaneLean.MathlibStatement